matrix:
  include:
    - os: linux
      sudo: required
      python: 3.9
      language: python
    - os: linux
      sudo: required
      python: 3.8
      language: python
    - os: linux
      dist: xenial
      sudo: required
      python: 3.7
      language: python

install:
  - python -m pip install -U pip
  - pip install -r requirements.txt

script:
  - coverage run src/wiki_search.py
  - coverage run tests/Unittest.py

after_success:
  - codecov
